#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

###################
### Merged from zprofile

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
    export LANG='en_CA.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  ~/bin
  /usr/local/{bin,sbin}
   /usr/sbin
    $path
    )

#
# Less
#

# Set the default Less options.
export LESS="-RMI"

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi


###################

# sticking custom completers in modules/completion so they're in my repo, not the external zsh-completions
fpath=(/usr/lib/prezto/modules/completion $fpath)

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# keep schtuff working with sudo
# (alternatively, sudo chsh to zsh)
# alias sudo='nocorrect sudo '

# for use with prompt, to only display $user when not me
DEFAULT_USER="cm"
