#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# keep schtuff working with sudo
# (alternatively, sudo chsh to zsh)
# alias sudo='nocorrect sudo '

DEFAULT_USER="cm"


