#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# HUB > Git
alias git=hub
if type compdef >/dev/null; then
   compdef hub=git
fi

# Git escape wonderfulness
autoload -Uz git-escape-magic
git-escape-magic
